#NumPy
* *NumPy* stands for Numerical Python. Numpy provides python with an extensive math library.
* NumPy ndarray are mutable.
* ndarray can be sliced.

##Why NumPy
* Speed: When performing operations on large arrays NumPy can often perform several orders of magnitude faster than Python lists. Reasons are memory efficient and optimized algorithms used by NumPy for doing arithmetic, statistical, and linear algebra operations.

* Mutlidimensional array: for representing *Vectors* and *Metrices*. *Data elements must be of a same type*. 

* Large number of optimized built-in mathematical functions. 
* Handle more data-types than python lists.


# Creating Array using numpy

In [ ]:
# import NumPy into Python
import numpy as np

# Create a 1D (Rank 1) ndarrays for integers only
x = np.array([1,2,3,4,5])

# Print ndarrays
print('x = {}'.format(x))

x = [1 2 3 4 5]


# Some useful Terminology
* Rank : 1D arrays refer as rank 1 arrays ... N-dimensional as rank N.
* Shape : Number of Rows and Columns

In [ ]:
print('x has dimension: ', x.shape)
print('x is an object of type : ', type(x))
print(' The elements in x are of type', x.dtype)


x has dimension:  (5,)
x is an object of type :  <class 'numpy.ndarray'>
 The elements in x are of type int64


In [ ]:
# Create rank 2 array
Y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print()
print('Y has dimension', Y.shape)
print('Y has total of {} elements'.format(Y.size))
print('Y is an object of type', type(Y))
print('The elements of Y are of type', Y.dtype)


Y has dimension (4, 3)
Y has total of 12 elements
Y is an object of type <class 'numpy.ndarray'>
The elements of Y are of type int64


In [ ]:
x = np.array([1,2,3])
y = np.array([1.2, 2.0, 3.3])
z = np.array([1,2.0,3])

print('The elements in x are of type', x.dtype)
print('The elements in y are of type', y.dtype)
print('The elements in z are of type', z.dtype)

The elements in x are of type int64
The elements in y are of type float64
The elements in z are of type float64


# Assigning particular data-type to array

In [ ]:
x = np.array([1.5, 2.2, 3.0, 4.99], dtype = np.int64)

print('The elements in x are of type', x.dtype)
print(x)

The elements in x are of type int64
[1 2 3 4]


# Storing array into a file and load operation

In [ ]:
x = np.array([1,2,3,4,5], dtype = np.int64)

# Saving into the current directory
np.save('my_array', x)

y = np.load('my_array.npy')

print('y is an object of type: ', type(y))
print('The elements in y are of type:', y.dtype)


y is an object of type:  <class 'numpy.ndarray'>
The elements in y are of type: int64


# Built-in Functions


## **Zeros**
np.zeros(shape)

In [ ]:
x = np.zeros((2,3))

print('x has dimension: ', x.shape)
print('x is an object of type', type(x))
print('The element in x are of type', x.dtype)
print(x)

x has dimension:  (2, 3)
x is an object of type <class 'numpy.ndarray'>
The element in x are of type float64
[[0. 0. 0.]
 [0. 0. 0.]]


## Ones
np.ones(shape)

In [ ]:
y = np.ones((5,3))

print('The Dimension of y is: ', y.shape)
print('y is an object of type : ', type(y))
print('The elements in y are of type : ', y.dtype)
print(y)

The Dimension of y is:  (5, 3)
y is an object of type :  <class 'numpy.ndarray'>
The elements in y are of type :  float64
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## ndarray of a Specified Number
np.full(shape)

In [ ]:
x = np.full((2,3),5)

print(x)

[[5 5 5]
 [5 5 5]]


## Other Useful Functions
 1. Identity matrix : Create square matrix that has 1s in the diagonal matrix and zeros eleswhere.
    * Syntax: np.eye(num) 

 2. Diagonal matrix : Create matrix with the desired diagonal values.
  * Syntax : np.diag([list])

 3. Range matrix : Create matrix of the range given as an input.
  * Syntax : np.arange(start,stop,step)
  * Array will be created for elements from start having evenly spaced as per the steps but exlude stop.

 4. Range with non-integer steps : Create matrix with non-integer steps.
  * Syntax : np.linspace(start, stop, N) 
    * Matrix creation done using start and stop input with space evenly distributed as per N. N is number of elements and not the steps. Both start and stop values are inlcuded for creating the matrix. 
    keyword 'endpoint = false' can be used to exclude the endpoint like an arange function.
    This function needs minimum start and stop input to create matrix and creates default N = 50 elements of the matrix array.
 
 5. Creating Rank 2 array : reshape function
  * Syntax : np.arrange(shape).reshape(new_shape) 
  
 6. Creating ndarray of random values (Floats) : random function
  * Syntax : np.random.random(shape) 
   creates an ndarray of the given shape with random floats in the half-open interval.

 7. Creating ndarray of random values (Integer) 
  * Syntax : np.random.randint(start, stop, size = shape)
  








## Accessing or Modifying elements in ndarray
  * The elements of the ndarray can be accessed or mdofiied by indexing.
  Elements can be accessed using indices inside square brackets []. Both positive and negative indices to access elements. Positive indices to access elements from the beginning and negative indices to access elements from the end.

## Deleting elements in ndarrays
  * Elements can be deleted in ndarray using delete function.
  * Syntax : np.delete(ndarray, elements, axis) 
    * axis = 0 -> row ; axis = 1 -> column

## Append to add row or column in ndarrays at the end
  * Syntax : np.append(ndarray, elements, axis)

## Insert elements to particular index
  * Syntax : np.insert(ndarray, index, elements, axis)

## Stacking ndarray
  * Syntax : Horizontal stacking "np.hstack((ndarray1, ndarray2))"
  * Syntax : Vertical stack " np.vstack((ndarray1, ndarray2)) "
  * The shape of both ndarray must match.  


## Slicing ndarrays
* for accessing subset of ndarrays.
* used colon ':' inside square bracket. 
* Slicing does not create a new ndarray, but it only creates a view of the original array. Thus a change in a slicing array also result in change in a original ndarray.
* np.copy() function is avaialble to create a new ndarray from existing one.


In [ ]:
import numpy as np

x = np.arange(25).reshape(5,5)

print('Original x = ', x)
print()
# Accessing an element in ndarray

print('First element of x is = ', x[0,0])
print('First row of x is = ', x[0])
print('First column of x is = ', x[:,0])
print('Last element of x is = ', x[-1,-1])
print('Last row of x is = ', x[-1])
print('Last column of x is = ', x[:,-1])

print()

# Modifying an element in ndarray

x[0,0] = 221
print('First element of x is modified to = ', x[0,0])
print('x modified to = ', x)

x[0] = 221
print('First row of x is modified to = ', x[0])
print('After modifying first row, x = ', x)


# Deleting an element in ndarray

print()

x = np.delete(x, 0, axis = 0)

print('After deletion of first row in x = ', x)

x = np.delete(x, [0,2], axis = 0)
print('Attempt to delete rows 0 and 1 ', x)

# Apend elements to ndarray
x = np.append(x, [range(5)], axis = 0)
print('After apend elements in x = ', x)

x = np.append(x, np.arange(3).reshape(3,1), axis = 1)
print('After append a column in x is = ', x)

# Insert elements in ndarray
x = np.insert(x,[1], range(5,11), axis = 0)
print()
print('x after inserting elements is = ', x)

Original x =  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

First element of x is =  0
First row of x is =  [0 1 2 3 4]
First column of x is =  [ 0  5 10 15 20]
Last element of x is =  24
Last row of x is =  [20 21 22 23 24]
Last column of x is =  [ 4  9 14 19 24]

First element of x is modified to =  221
x modified to =  [[221   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]]
First row of x is modified to =  [221 221 221 221 221]
After modifying first row, x =  [[221 221 221 221 221]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]]

After deletion of first row in x =  [[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Attempt to delete rows 0 and 1  [[10 11 12 13 14]
 [20 21 22 23 24]]
After apend elements in x =  [[10 11 12 13 14]
 [20 21 22 23 24]
 [ 0  1  2  3  4]]
After append a column in x is =  [[10 11 12 13 1

## Boolean operation on ndarrays


### Boolean operation

In [ ]:
print('origianl ndarray x = ', x)
print()
print('\n')
print('Elements in x greater than 10 are = ', x[x > 10])

print()

print('Elements in x > 15 & x <= 20 are = ', x[(x > 15) & (x <= 20)])

x[(x >15) & (x <= 22)] = 45

print()
print('Element in range 15-22 changed to 45 and x = \n', x)

origianl ndarray x =  [[10 11 12 13 14  0]
 [ 5  6  7  8  9 10]
 [45 45 45 23 24  1]
 [ 0  1  2  3  4  2]]



Elements in x greater than 10 are =  [11 12 13 14 45 45 45 23 24]

Elements in x > 15 & x <= 20 are =  []

Element in range 15-22 changed to 45 and x = 
 [[10 11 12 13 14  0]
 [ 5  6  7  8  9 10]
 [45 45 45 23 24  1]
 [ 0  1  2  3  4  2]]


### Comparing ndarrays

In [ ]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,5,4])

print('x = \n', x)
print()
print('y = \n', y)
print()

print('The elements that are both in x and y : ', np.intersect1d(x, y))
print()
print('The elements that are in x but not in y : ', np.setdiff1d(x,y))
print()
print('All the elements of x and y : ', np.union1d(x, y))


x = 
 [1 2 3 4 5]

y = 
 [6 7 2 5 4]

The elements that are both in x and y :  [2 4 5]

The elements that are in x but not in y :  [1 3]

All the elements of x and y :  [1 2 3 4 5 6 7]


### sorting ndarray

In [ ]:
x = np.random.randint(25,88,20)
print(x)

print()
print('Sorted x (out of place): ', np.sort(x))

print()

print('ndarray x after np.sort(x) is = \n ', x)

print()

print('Sort operation on x = ', x.sort())

print()

print('ndarray after x.sort() is : \n', x)

[46 38 43 59 52 56 81 70 25 69 29 85 67 67 54 78 69 54 56 71]

Sorted x (out of place):  [25 29 38 43 46 52 54 54 56 56 59 67 67 69 69 70 71 78 81 85]

ndarray x after np.sort(x) is = 
  [46 38 43 59 52 56 81 70 25 69 29 85 67 67 54 78 69 54 56 71]

Sort operation on x =  None

ndarray after x.sort() is : 
 [25 29 38 43 46 52 54 54 56 56 59 67 67 69 69 70 71 78 81 85]


### Pick odd example

In [ ]:
x = np.arange(1,26).reshape(5,5)
print(x)

print()

print('Odd valuea in x are = ', x[x % 2 != 0])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Odd valuea in x are =  [ 1  3  5  7  9 11 13 15 17 19 21 23 25]


## Arithmetic operations and Broadcasting
* Elements wise operation as well as matrix operations are possible.
* Broadcasting method is used for the elements wise operations on ndarrays of different shapes.
* np.add() or '+', np.subtract() or '-', np.multiply() or '*', np.divide() or '/'
* Some other functions are : Squareroot, exponential, power to.
* np.sqrt(), np.exp(), np.power()


