**Decision Tree Classification algorithm**  Notebook exercise pratice at Cognitive Class AI Machine Learning Online course

**Decision Tree** are build using recursive partitioning to classify the data. Choice of attribute to split the data is very important to the purity of the leaves. Impurity of Node is calculated by Entropy of data.
**Entropy**is the amount of information disorder or the amount of randomness in the data(Homogenity of data). If data is homogenous than $$Entropy = 0$$ and if data is equally devided than $$Entropy = 1$$
**Information Gain** is the information that can increase the level of certaininty after splitting. 


**Dataset** used for algorithm practice is a Medical Research report on different drugs category given to the patients based on the symptoms.
*https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/drug200.csv*

In [24]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [25]:
path = 'https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/drug200.csv'
df = pd.read_csv(path)
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [26]:
df.shape

(200, 6)

In [27]:
df.columns

Index(['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K', 'Drug'], dtype='object')

In [28]:
X = df[['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']].values
X[0:5]

array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.113999999999999],
       [28, 'F', 'NORMAL', 'HIGH', 7.797999999999999],
       [61, 'F', 'LOW', 'HIGH', 18.043]], dtype=object)

Sklearn Decision Tree do not handle categorical varaibles (**Sex, BP, Cholesterol**). Sklearn **LabelEncoder()** Encode target labels with numeric value between 0 and n_class-1. .

In [29]:
from sklearn import preprocessing
le_sex = preprocessing.LabelEncoder()
le_sex.fit(['F', 'M'])
X[:, 1] = le_sex.transform(X[:, 1])

In [30]:
X[0:5]

array([[23, 0, 'HIGH', 'HIGH', 25.355],
       [47, 1, 'LOW', 'HIGH', 13.093],
       [47, 1, 'LOW', 'HIGH', 10.113999999999999],
       [28, 0, 'NORMAL', 'HIGH', 7.797999999999999],
       [61, 0, 'LOW', 'HIGH', 18.043]], dtype=object)

In [31]:
le_BP = preprocessing.LabelEncoder().fit(['LOW', 'NORMAL', 'HIGH'])
X[:, 2] = le_BP.transform(X[:,2])
X[0:5]

array([[23, 0, 0, 'HIGH', 25.355],
       [47, 1, 1, 'HIGH', 13.093],
       [47, 1, 1, 'HIGH', 10.113999999999999],
       [28, 0, 2, 'HIGH', 7.797999999999999],
       [61, 0, 1, 'HIGH', 18.043]], dtype=object)

In [32]:
X[:,3] = preprocessing.LabelEncoder().fit(['NORMAL', 'HIGH']).transform(X[:,3])

In [33]:
X[0:5]

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.113999999999999],
       [28, 0, 2, 0, 7.797999999999999],
       [61, 0, 1, 0, 18.043]], dtype=object)

In [38]:
y = df['Drug']

In [39]:
y[0:5]

0    drugY
1    drugC
2    drugC
3    drugX
4    drugY
Name: Drug, dtype: object

### Setting up the Decision Tree

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size = 0.3, random_state =3)

**Modeling**

In [43]:
drugTree = DecisionTreeClassifier(criterion = 'entropy', max_depth = 4)
drugTree

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=4, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [44]:
drugTree.fit(X_trainset, y_trainset)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=4, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [45]:
predTree = drugTree.predict(X_testset)

In [49]:
print(predTree[0:5])
print()
print(y_testset[0:5])

['drugY' 'drugX' 'drugX' 'drugX' 'drugX']

40     drugY
51     drugX
139    drugX
197    drugX
170    drugX
Name: Drug, dtype: object


**Evaluation**

In [50]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("Decision Tree's Accuracy: ", metrics.accuracy_score(y_testset, predTree))

Decision Tree's Accuracy:  0.9833333333333333
